<!DOCTYPE html>
<html lang="zh-CN">
<head lang="zh-CN">
    <title><?php echo $page_data['header']->get_title(); ?></title>

	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="<?php echo $page_data['header']->get_description(); ?>">
	<meta name="keywords" content="<?php echo $page_data['header']->get_keywords(); ?>">
	<meta name="author" content="Siglud Siglud@gmail.com">

	<script src="http://libs.baidu.com/jquery/2.0.3/jquery.min.js"></script>
	<script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
	<link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<header>
	<div class="container"></div>
</header>
<?php template_content_require($target, $page_data) ?>
<?php template_footer() ?>
</body>
</html>