<div class="container">
	<table class="table table-striped table-bordered table-hover">
		<thead>
		<tr>
			<th></th>
			<th>发布时间</th>
			<th>分类</th>
			<th>名称</th>
			<th>文件大小</th>
			<th>种子</th>
			<th>下载</th>
			<th>发布者</th>
		</tr>
		</thead>
		<tbody>
		<?php /** @var popgo\ShareList $share_info */
		foreach($page_data['anime_list'] as $share_info){ ?>
		<tr>
			<td><a href="<?php echo $share_info->getShareInfo()->get_magnet(); ?>"></a></td>
			<td><?php echo $share_info->getShareInfo()->get_add_time()->get_man_time(); ?></td>
			<td><?php echo $share_info->getCategoryInfo()->get_category_name()->get_html_escape_text(); ?></td>
			<td><?php echo $share_info->getShareInfo()->get_share_name()->get_html_escape_text(); ?></td>
			<td><?php echo $share_info->getShareInfo()->get_file_size(); ?></td>
			<td><?php echo $share_info->getDownloadInfo()->get_seeder_number(); ?></td>
			<td><?php echo $share_info->getDownloadInfo()->get_leechers_number(); ?></td>
			<td><a href="/uploader-<?php echo $share_info->getUserInfo()->getUserId() ?>-1-<?php echo $share_info->getUserInfo()->getUserName()->get_url_encode_text() ?>.html" target="_blank"><?php echo $share_info->getUserInfo()->getUserName()->get_html_escape_text(); ?></a></td>
		</tr>
		<?php } ?>
		</tbody>
	</table>

	<table class="table table-striped table-bordered table-hover">
		<thead>
		<tr>
			<th></th>
			<th>发布时间</th>
			<th>分类</th>
			<th>名称</th>
			<th>文件大小</th>
			<th>做种者</th>
			<th>下载者</th>
			<th>发布者</th>
		</tr>
		</thead>
		<tbody>
		<?php /** @var popgo\ShareList $share_info */
		foreach($page_data['anime_list'] as $share_info){ ?>
		<tr>
			<td></td>
			<td><?php echo $share_info->getShareInfo()->get_add_time()->get_man_time(); ?></td>
			<td><?php echo $share_info->getCategoryInfo()->get_category_name()->get_html_escape_text(); ?></td>
			<td><?php echo $share_info->getShareInfo()->get_share_name()->get_html_escape_text(); ?></td>
			<td><?php echo $share_info->getShareInfo()->get_file_size(); ?></td>
			<td></td>
			<td></td>
			<td><a href="/uploader-<?php echo $share_info->getUserInfo()->getUserId() ?>-1-<?php echo $share_info->getUserInfo()->getUserName()->get_url_encode_text() ?>.html" target="_blank"><?php echo $share_info->getUserInfo()->getUserName()->get_html_escape_text(); ?></a></td>
		</tr>
		<?php } ?>
		</tbody>
	</table>
</div>